#!/usr/bin/env bash
#install nginx
apt-get udpate
apt-get install -y nginx
ufw allow 'Nginx HTTP'

#create directory where our pages will be stored
echo "301 Moved Permanently" > /etc/nginx/html/index.html

sed -i '38i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4  permanent;' /etc/nginx/sites-available/default
#reload nginx
service nginx restart
