#!/usr/bin/env bash
# The redirection as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        rewrite ^redirect_me(.*) https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
