#!/usr/bin/env bash

# Update the apt package index and install nginx
apt-get -y update
apt-get -y install nginx

# Create a file called redirect.conf in the /etc/nginx/sites-available directory
echo "server {
  listen 80;

  location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
}" > /etc/nginx/sites-available/redirect.conf

# Enable the redirect.conf file
ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/redirect.conf

# Restart the nginx service
service nginx restart
